using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Client.UserInterface.Controls;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Content.Client.Vanilla.AlertKey
{
    [GenerateTypedNameReferences]
    public sealed partial class AlertKeyMenu : FancyWindow
    {
        public AlertKeyMenu()
        {
        }

    }
}
