//rayten-start
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class MedipenTooltip : Control
{
    public MedipenTooltip(string tooltip)
    {
        RobustXamlLoader.Load(this);

        MedipenTooltipLabel.SetMarkup(tooltip);
    }
}
//rayten-end